[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/.netlify/functions/state"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET,POST,PUT,PATCH,OPTIONS"
  Access-Control-Allow-Headers = "content-type"
[[headers]]
  for = "/.netlify/functions/sms"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "POST,OPTIONS"
  Access-Control-Allow-Headers = "content-type"
